services:
  backend:
    build: ./backend
    environment:
      - TZ=America/Sao_Paulo
      - MASTER_EMAIL=${MASTER_EMAIL:-simplificaautomacoes@gmail.com}
      - MASTER_PASSWORD=${MASTER_PASSWORD:-123456}
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend_data:
